- alias: vorobievoff
  trigger:
    - platform: state
      entity_id: binary_sensor.vorv_router
      to: 'off'  
    
  action:
    - service: notify.home_vorobiev
      data:
        title: Warning!
        message: Не доступен Host1!

- alias: vorobiev_on
  trigger:
    - platform: state
      entity_id: binary_sensor.vorv_router
      to: 'on'

  action:
    - service: notify.home_vorobiev
      data:
        title: OK!
        message: Host1 доступен!


- alias: mqtt_tco1
  trigger: 
    - platform: time
      minutes: '/1'
      seconds: 00
  action: 
    - service: mqtt.publish
      data:
        topic: "esp8266_tco1/temp"
        payload_template: ' {{ states.sensor.esp8266_tco1.state }} '
        retain: true



- id: hass_theme
  alias: hass_theme
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.hass_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.hass_theme.state }}"
