- platform: ping
  host: 212.113.253.230
  name: dorv_router

- platform: ping
  host: 192.168.16.1
  name: vorv_router

- platform: ping
  host: 192.168.16.250 
  name: vorv_rpi

- platform: ping
  host: 192.168.16.63
  name: vorv_sonoff1
