- platform: generic_thermostat
  name: home1_c
  heater:  switch.home1_sw
  target_sensor: sensor.home1_t
  min_temp: 15
  max_temp: 30
  ac_mode: False
  target_temp: 17
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_operation_mode: "off"
  away_temp: 16
