
#  - platform: rest
#    scan_interval: 1
#    resource: http://127.0.0.1:5500/firstbt/swts/SW1
#    name: M1SW1
#    body_on: "true\n"
#    body_off: "false\n"

#- platform: broadlink
#  host: 192.168.1.230
#  mac: 'EB:43:f4:34:EA:34'
#  timeout: 80
#  switches:
#      came_up: 
#        friendly_name: "cameUP"
#        command_on: 'shA0ABAtLw8RLS8PEC0RLS8PLw8vDy8PLg8vDxEtES0vDy8PLw8vDxAuEC0QAAHQLw8vDxAtEC4AAAAA'

- platform: mqtt
  name: sonoff1
  friendly_name: "Sonoff_1"
  state_topic: "sonoff/room1/relay/0"
  command_topic: "sonoff/room1/relay/0/set"
  payload_on: 1
  payload_off: 0
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: esp8266_tco1_sw
  state_topic: "stat/esp8266_tco1/POWER"
  command_topic: "cmnd/esp8266_tco1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: wake_on_lan
  mac_address: "b8-27-eb-b4-8e-4c"
  name: kodi_on
